{% set name = "r-seuratdisk" %}
{% set version = "0.0.9021" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mojaveazure/seurat-disk/archive/877d4e18ab38c686f5db54f8cd290274ccdbe295.tar.gz
  sha256: d2d6b6604e8a1f6de90956d0401d34b51b07b30671a445d0e06876f2dec999ac

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  script: "R CMD INSTALL --build ."

requirements:
    host:
        - r-base
        - r-cli
        - r-seurat
        - r-seuratobject >=3.2.0
        - r-devtools
        - r-crayon
        - r-hdf5r
        - r-matrix
        - r-r6
        - r-rlang
        - r-stringi
        - r-withr
    run:
        - r-base
        - r-cli
        - r-seurat
        - r-seuratobject >=3.2.0
        - r-crayon
        - r-hdf5r
        - r-matrix
        - r-r6
        - r-rlang
        - r-stringi
        - r-withr

test:
    commands:
        - $R -e 'library(Seurat)'
        - $R -e 'library(SeuratDisk)'

about:
  home: https://github.com/mojaveazure/seurat-disk
  dev_url: https://github.com/mojaveazure/seurat-disk
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: 'Support for multi-modal single cell through h5Seurat and AnnData for Seurat'
  description: | 
        The h5Seurat file format is specifically designed for the storage and
        analysis of multi-modal single-cell and spatially-resolved expression 
        experiments, for example, from CITE-seq or 10X Visium technologies. It 
        holds all molecular information and associated metadata, including (for 
        example) nearest-neighbor graphs, dimensional reduction information, 
        spatial coordinates and image data, and cluster labels. We also support 
        rapid and on-disk conversion between h5Seurat and AnnData objects, 
        with the goal of enhancing interoperability between Seurat and Scanpy. 
extra:
  recipe-maintainers:
    - danielnachun
    - pcm32
